name: Build LaTeX PDF
on:
  push:
    branches: [ "main", "repo-refresh/infra-docs-v0.1.0" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install TeX
        run: sudo apt-get update && sudo apt-get install -y texlive-full latexmk
      - name: Build
        working-directory: paper
        run: latexmk -pdf -interaction=nonstopmode main.tex
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: QMNET-preprint
          path: paper/main.pdf
